# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  description: |
    LMF Broadcast Service.
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  title: LMF Broadcast
  version: 1.2.0-alpha.1
externalDocs:
  description: 3GPP TS 29.572 V18.0.0; 5G System; Location Management Services; Stage
    3
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.572/
servers:
- url: "{apiRoot}/nlmf-broadcast/v1"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
paths:
  /cipher-key-data:
    post:
      callbacks:
        CipheringKeyData:
          '{$request.body#/amfCallBackURI}':
            post:
              operationId: CipheringKeyDataPost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CipheringKeyInfo"
                description: Ciphering Key Data Notification
              responses:
                "200":
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/CipheringKeyResponse"
                  description: Expected response to a valid request
                "307":
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/RedirectResponse"
                  description: Temporary Redirect
                  headers:
                    Location:
                      description: The URI pointing to the resource located on the
                        redirect target
                      required: true
                      schema:
                        type: string
                    "3gpp-Sbi-Target-Nf-Id":
                      description: |
                        'Identifier of target NF (service) instance towards which the request is redirected'
                      schema:
                        type: string
                "308":
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/RedirectResponse"
                  description: Permanent Redirect
                  headers:
                    Location:
                      description: The URI pointing to the resource located on the
                        redirect target
                      required: true
                      schema:
                        type: string
                    "3gpp-Sbi-Target-Nf-Id":
                      description: |
                        'Identifier of target NF (service) instance towards which the request is redirected'
                      schema:
                        type: string
                "400":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Bad request
                "401":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Unauthorized
                "403":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Forbidden
                "404":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Not Found
                "411":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Length Required
                "413":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Content Too Large
                "415":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Unsupported Media Type
                "429":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Too Many Requests
                "500":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Internal Server Error
                "502":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Bad Gateway
                "503":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Service Unavailable
                "504":
                  content:
                    application/problem+json:
                      schema:
                        $ref: "#/components/schemas/ProblemDetails"
                  description: Gateway Timeout
                default:
                  description: Generic Error
              x-callback-request: true
      operationId: CipheringKeyData
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CipherRequestData"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CipherResponseData"
          description: Expected response to a valid request
        "307":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RedirectResponse"
          description: Temporary Redirect
          headers:
            Location:
              description: The URI pointing to the resource located on the redirect
                target
              required: true
              schema:
                type: string
            "3gpp-Sbi-Target-Nf-Id":
              description: |
                'Identifier of target NF (service) instance towards which the request is redirected'
              schema:
                type: string
        "308":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RedirectResponse"
          description: Permanent Redirect
          headers:
            Location:
              description: The URI pointing to the resource located on the redirect
                target
              required: true
              schema:
                type: string
            "3gpp-Sbi-Target-Nf-Id":
              description: |
                'Identifier of target NF (service) instance towards which the request is redirected'
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Content Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Internal Server Error
        "502":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Bad Gateway
        "503":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Service Unavailable
        "504":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
          description: Gateway Timeout
        default:
          description: Generic Error
      summary: Request ciphering key data
      tags:
      - Request Ciphering Key Data
components:
  responses:
    "307":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RedirectResponse"
      description: Temporary Redirect
      headers:
        Location:
          description: The URI pointing to the resource located on the redirect target
          required: true
          schema:
            type: string
        "3gpp-Sbi-Target-Nf-Id":
          description: |
            'Identifier of target NF (service) instance towards which the request is redirected'
          schema:
            type: string
    "308":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RedirectResponse"
      description: Permanent Redirect
      headers:
        Location:
          description: The URI pointing to the resource located on the redirect target
          required: true
          schema:
            type: string
        "3gpp-Sbi-Target-Nf-Id":
          description: |
            'Identifier of target NF (service) instance towards which the request is redirected'
          schema:
            type: string
    "400":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Bad request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Forbidden
    "404":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Not Found
    "411":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Length Required
    "413":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Content Too Large
    "415":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Unsupported Media Type
    "429":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Too Many Requests
    "500":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Internal Server Error
    "502":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Bad Gateway
    "503":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Service Unavailable
    "504":
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
      description: Gateway Timeout
    default:
      description: Generic Error
  schemas:
    CipheringKeyInfo:
      description: Information within Ciphering Key Data Notification request.
      example:
        cipheringData:
        - ltePosSibTypes: null
          nrPosSibTypes: null
          cipheringSetID: null
          validityDuration: null
          validityStartTime: null
          c0: null
          cipheringKey: null
          taiList: null
        - ltePosSibTypes: null
          nrPosSibTypes: null
          cipheringSetID: null
          validityDuration: null
          validityStartTime: null
          c0: null
          cipheringKey: null
          taiList: null
        supportedFeatures: supportedFeatures
      properties:
        cipheringData:
          items:
            $ref: "#/components/schemas/CipheringDataSet"
          minItems: 1
          type: array
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      required:
      - cipheringData
      type: object
    CipheringKeyResponse:
      description: Information within Ciphering Key Data Notification Response.
      example:
        cipheringDataReport:
        - storageOutcome: STORAGE_SUCCESSFUL
          cipheringSetID: null
        - storageOutcome: STORAGE_SUCCESSFUL
          cipheringSetID: null
      properties:
        cipheringDataReport:
          items:
            $ref: "#/components/schemas/CipheringSetReport"
          minItems: 1
          type: array
      type: object
    CipheringDataSet:
      description: Represents a Ciphering Data Set.
      example:
        ltePosSibTypes: null
        nrPosSibTypes: null
        cipheringSetID: null
        validityDuration: null
        validityStartTime: null
        c0: null
        cipheringKey: null
        taiList: null
      properties:
        cipheringSetID:
          $ref: "#/components/schemas/CipheringSetID"
        cipheringKey:
          $ref: "#/components/schemas/CipheringKey"
        c0:
          $ref: "#/components/schemas/C0"
        ltePosSibTypes:
          $ref: "#/components/schemas/Bytes"
        nrPosSibTypes:
          $ref: "#/components/schemas/Bytes"
        validityStartTime:
          $ref: "#/components/schemas/DateTime"
        validityDuration:
          $ref: "#/components/schemas/ValidityDuration"
        taiList:
          $ref: "#/components/schemas/Bytes"
      required:
      - c0
      - cipheringKey
      - cipheringSetID
      - validityDuration
      - validityStartTime
      type: object
    CipheringSetReport:
      description: Represents a report of Ciphering Data Set storage.
      example:
        storageOutcome: STORAGE_SUCCESSFUL
        cipheringSetID: null
      properties:
        cipheringSetID:
          $ref: "#/components/schemas/CipheringSetID"
        storageOutcome:
          $ref: "#/components/schemas/StorageOutcome"
      required:
      - cipheringSetID
      - storageOutcome
      type: object
    CipherRequestData:
      description: Information within Ciphering Key Data request.
      example:
        amfCallBackURI: amfCallBackURI
        supportedFeatures: supportedFeatures
      properties:
        amfCallBackURI:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      required:
      - amfCallBackURI
      type: object
    CipherResponseData:
      description: Information within Ciphering Key Data Response.
      example:
        dataAvailability: CIPHERING_KEY_DATA_AVAILABLE
      properties:
        dataAvailability:
          $ref: "#/components/schemas/DataAvailability"
      required:
      - dataAvailability
      type: object
    CipheringSetID:
      description: Ciphering Data Set Identifier.
      maximum: 65535
      minimum: 0
      type: integer
    CipheringKey:
      description: Ciphering Key.
      format: byte
      type: string
    C0:
      description: First component of the initial ciphering counter.
      format: byte
      type: string
    ValidityDuration:
      description: Validity Duration of the Ciphering Data Set.
      maximum: 65535
      minimum: 1
      type: integer
    StorageOutcome:
      enum:
      - STORAGE_SUCCESSFUL
      - STORAGE_FAILED
      type: string
    DataAvailability:
      enum:
      - CIPHERING_KEY_DATA_AVAILABLE
      - CIPHERING_KEY_DATA_NOT_AVAILABLE
      type: string
    RedirectResponse:
      description: |
        The response shall include a Location header field containing a different URI (pointing to a different URI of an other service instance), or the same URI if a request is redirected to the same target resource via a different SCP.
      example:
        targetSepp: null
        cause: cause
        targetScp: null
      properties:
        cause:
          type: string
        targetScp:
          $ref: "#/components/schemas/Uri"
        targetSepp:
          $ref: "#/components/schemas/Uri"
      type: object
    Uri:
      description: String providing an URI formatted according to RFC 3986.
      type: string
    ProblemDetails:
      description: Provides additional information in an error response.
      properties:
        type:
          $ref: "#/components/schemas/Uri"
        title:
          type: string
        status:
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          $ref: "#/components/schemas/Uri"
        cause:
          description: |
            A machine-readable application error cause specific to this occurrence of the problem. This IE should be present and provide application-related error information, if available.
          type: string
        invalidParams:
          items:
            $ref: "#/components/schemas/InvalidParam"
          minItems: 1
          type: array
        supportedFeatures:
          $ref: "#/components/schemas/SupportedFeatures"
        accessTokenError:
          $ref: "#/components/schemas/AccessTokenErr"
        accessTokenRequest:
          $ref: "#/components/schemas/AccessTokenReq"
        nrfId:
          $ref: "#/components/schemas/Fqdn"
        supportedApiVersions:
          items:
            type: string
          minItems: 1
          type: array
        noProfileMatchInfo:
          $ref: "#/components/schemas/NoProfileMatchInfo"
      type: object
    InvalidParam:
      description: It contains an invalid parameter and a related description.
      properties:
        param:
          description: |
            If the invalid parameter is an attribute in a JSON body, this IE shall contain the attribute's name and shall be encoded as a JSON Pointer. If the invalid parameter is an HTTP header, this IE shall be formatted as the concatenation of the string "header " plus the name of such header. If the invalid parameter is a query parameter, this IE shall be formatted as the concatenation of the string "query " plus the name of such query parameter. If the invalid parameter is a variable part in the path of a resource URI, this IE shall contain the name of the variable, including the symbols "{" and "}" used in OpenAPI specification as the notation to represent variable path segments.
          type: string
        reason:
          description: |
            A human-readable reason, e.g. "must be a positive integer". In cases involving failed operations in a PATCH request, the reason string should identify the operation that failed using the operation's array index to assist in correlation of the invalid parameter with the failed operation, e.g." Replacement value invalid for attribute (failed operation index= 4)"
          type: string
      required:
      - param
      type: object
    SupportedFeatures:
      description: |
        A string used to indicate the features supported by an API that is used as defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in hexadecimal representation Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
      pattern: "^[A-Fa-f0-9]*$"
      type: string
    Fqdn:
      description: Fully Qualified Domain Name
      maxLength: 253
      minLength: 4
      pattern: "^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\.)+[A-Za-z]{2,63}\\\
        .?$"
      type: string
    Bytes:
      description: string with format 'bytes' as defined in OpenAPI
      format: byte
      type: string
    DateTime:
      description: string with format 'date-time' as defined in OpenAPI.
      format: date-time
      type: string
    AccessTokenErr:
      description: Error returned in the access token response message
      properties:
        error:
          enum:
          - invalid_request
          - invalid_client
          - invalid_grant
          - unauthorized_client
          - unsupported_grant_type
          - invalid_scope
          type: string
        error_description:
          type: string
        error_uri:
          type: string
      required:
      - error
      type: object
    AccessTokenReq:
      description: Contains information related to the access token request
      properties:
        grant_type:
          enum:
          - client_credentials
          type: string
        nfInstanceId:
          $ref: "#/components/schemas/NfInstanceId"
        nfType:
          $ref: "#/components/schemas/NFType"
        targetNfType:
          $ref: "#/components/schemas/NFType"
        scope:
          pattern: "^([a-zA-Z0-9_:-]+)( [a-zA-Z0-9_:-]+)*$"
          type: string
        targetNfInstanceId:
          $ref: "#/components/schemas/NfInstanceId"
        requesterPlmn:
          $ref: "#/components/schemas/PlmnId"
        requesterPlmnList:
          items:
            $ref: "#/components/schemas/PlmnId"
          minItems: 2
          type: array
        requesterSnssaiList:
          items:
            $ref: "#/components/schemas/Snssai"
          minItems: 1
          type: array
        requesterFqdn:
          $ref: "#/components/schemas/Fqdn"
        requesterSnpnList:
          items:
            $ref: "#/components/schemas/PlmnIdNid"
          minItems: 1
          type: array
        targetPlmn:
          $ref: "#/components/schemas/PlmnId"
        targetSnpn:
          $ref: "#/components/schemas/PlmnIdNid"
        targetSnssaiList:
          items:
            $ref: "#/components/schemas/Snssai"
          minItems: 1
          type: array
        targetNsiList:
          items:
            type: string
          minItems: 1
          type: array
        targetNfSetId:
          $ref: "#/components/schemas/NfSetId"
        targetNfServiceSetId:
          $ref: "#/components/schemas/NfServiceSetId"
        hnrfAccessTokenUri:
          $ref: "#/components/schemas/Uri"
        sourceNfInstanceId:
          $ref: "#/components/schemas/NfInstanceId"
      required:
      - grant_type
      - nfInstanceId
      - scope
      type: object
    NoProfileMatchInfo:
      description: Provides the reason for not finding NF matching the search criteria
      properties:
        reason:
          $ref: "#/components/schemas/NoProfileMatchReason"
        queryParamCombinationList:
          items:
            $ref: "#/components/schemas/QueryParamCombination"
          minItems: 1
          type: array
      required:
      - reason
      type: object
    NoProfileMatchReason:
      description: No Profile Match Reason
      enum:
      - REQUESTER_PLMN_NOT_ALLOWED
      - TARGET_NF_SUSPENDED
      - TARGET_NF_UNDISCOVERABLE
      - QUERY_PARAMS_COMBINATION_NO_MATCH
      - TARGET_NF_TYPE_NOT_SUPPORTED
      - UNSPECIFIED
      type: string
    QueryParamCombination:
      description: Contains a list of Query Parameters
      properties:
        queryParams:
          items:
            $ref: "#/components/schemas/QueryParameter"
          minItems: 1
          type: array
      required:
      - queryParams
      type: object
    QueryParameter:
      description: Contains the name and value of a query parameter
      properties:
        name:
          type: string
        value:
          type: string
      required:
      - name
      - value
      type: object
    NfInstanceId:
      description: |
        String uniquely identifying a NF instance. The format of the NF Instance ID shall be a Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
      format: uuid
      type: string
    NFType:
      description: NF types known to NRF
      enum:
      - NRF
      - UDM
      - AMF
      - SMF
      - AUSF
      - NEF
      - PCF
      - SMSF
      - NSSF
      - UDR
      - LMF
      - GMLC
      - 5G_EIR
      - SEPP
      - UPF
      - N3IWF
      - AF
      - UDSF
      - BSF
      - CHF
      - NWDAF
      - PCSCF
      - CBCF
      - HSS
      - UCMF
      - SOR_AF
      - SPAF
      - MME
      - SCSAS
      - SCEF
      - SCP
      - NSSAAF
      - ICSCF
      - SCSCF
      - DRA
      - IMS_AS
      - AANF
      - 5G_DDNMF
      - NSACF
      - MFAF
      - EASDF
      - DCCF
      - MB_SMF
      - TSCTSF
      - ADRF
      - GBA_BSF
      - CEF
      - MB_UPF
      - NSWOF
      - PKMF
      - MNPF
      - SMS_GMSC
      - SMS_IWMSC
      - MBSF
      - MBSTF
      - PANF
      - IP_SM_GW
      - SMS_ROUTER
      - DCSF
      - MRF
      - MRFP
      - MF
      - SLPKMF
      - RH
      type: string
    PlmnId:
      description: |
        When PlmnId needs to be converted to string (e.g. when used in maps as key), the string shall be composed of three digits "mcc" followed by "-" and two or three digits "mnc".
      properties:
        mcc:
          $ref: "#/components/schemas/Mcc"
        mnc:
          $ref: "#/components/schemas/Mnc"
      required:
      - mcc
      - mnc
      type: object
    Mcc:
      description: |
        Mobile Country Code part of the PLMN, comprising 3 digits, as defined in clause 9.3.3.5 of 3GPP TS 38.413.
      pattern: "^\\d{3}$"
      type: string
    Mnc:
      description: |
        Mobile Network Code part of the PLMN, comprising 2 or 3 digits, as defined in clause 9.3.3.5 of 3GPP TS 38.413.
      pattern: "^\\d{2,3}$"
      type: string
    Snssai:
      description: |
        When Snssai needs to be converted to string (e.g. when used in maps as key), the string shall be composed of one to three digits "sst" optionally followed by "-" and 6 hexadecimal digits "sd".
      properties:
        sst:
          description: |
            Unsigned integer, within the range 0 to 255, representing the Slice/Service Type. It indicates the expected Network Slice behaviour in terms of features and services. Values 0 to 127 correspond to the standardized SST range. Values 128 to 255 correspond to the Operator-specific range. See clause 28.4.2 of 3GPP TS 23.003. Standardized values are defined in clause 5.15.2.2 of 3GPP TS 23.501.
          maximum: 255
          minimum: 0
          type: integer
        sd:
          description: |
            3-octet string, representing the Slice Differentiator, in hexadecimal representation. Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent 4 bits. The most significant character representing the 4 most significant bits of the SD shall appear first in the string, and the character representing the 4 least significant bit of the SD shall appear last in the string. This is an optional parameter that complements the Slice/Service type(s) to allow to differentiate amongst multiple Network Slices of the same Slice/Service type. This IE shall be absent if no SD value is associated with the SST.
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
      required:
      - sst
      type: object
    PlmnIdNid:
      description: |
        Contains the serving core network operator PLMN ID and, for an SNPN, the NID that together with the PLMN ID identifies the SNPN.
      properties:
        mcc:
          $ref: "#/components/schemas/Mcc"
        mnc:
          $ref: "#/components/schemas/Mnc"
        nid:
          $ref: "#/components/schemas/Nid"
      required:
      - mcc
      - mnc
      type: object
    Nid:
      description: |
        This represents the Network Identifier, which together with a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501 clause 5.30.2.1).
      pattern: "^[A-Fa-f0-9]{11}$"
      type: string
    NfSetId:
      description: |
        NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string "set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>", or "set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>" with <MCC> encoded as defined in clause 5.4.2 ("Mcc" data type definition) <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.
          If there are only 2 significant digits in the MNC, one "0" digit shall be inserted
          at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$'
        <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but
          with lower case characters <Set ID> encoded as a string of characters consisting of
          alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that
          shall end with either an alphabetic character or a digit.
      type: string
    NfServiceSetId:
      description: |
        NF Service Set Identifier (see clause 28.12 of 3GPP TS 23.003) formatted as the following string "set<Set ID>.sn<Service Name>.nfi<NF Instance ID>.5gc.mnc<MNC>.mcc<MCC>", or "set<SetID>.sn<ServiceName>.nfi<NFInstanceID>.5gc.nid<NID>.mnc<MNC>.mcc<MCC>" with <MCC> encoded as defined in clause 5.4.2 ("Mcc" data type definition) <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.
          If there are only 2 significant digits in the MNC, one "0" digit shall be inserted
          at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$'
        <NID> encoded as defined in clause 5.4.2 ("Nid" data type definition) <NFInstanceId> encoded as defined in clause 5.3.2 <ServiceName> encoded as defined in 3GPP TS 29.510 <Set ID> encoded as a string of characters consisting of alphabetic
          characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that shall end
          with either an alphabetic character or a digit.
      type: string
